apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- name: controller
  newName: quay.io/prismacloud/pcc-operator
  digest: sha256:51a343d5ea0115e3c43ccaa546492e85ab74cf2cf2658d725c1ea7099fc89191
